language: java
jdk: openjdk11
sudo: required

services:
  - docker
  - postgresql

before_script:
  - psql -c 'create database notification_service;' -U postgres

env:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/notification_service

after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: "hedviginsurance"
    token:
      secure: "NpqMRpqmS/8Sn0ujagzYgC6qJ4ImiyCQK+83w8YMG3UfZqCXxvekhDPUEFwWAf85j3ypbSfX8qZUVs1E5QOBiLH5DPS808JMtemHrcyP0dk+f9bPM8vtPeW91ybgz8QyfGjqXpyf0dw2vGsjl04zISjXIFEYqlBOFS2YgeLmn2621iUiqRBDXVl/fTyvySxBgMrL+4Q4ELS4Wjtyrvd/G0HxAlm582KL08hg9ro9pTblx8hxc4nsgpMGEf/dys5q8jpvzsjx3qpyWBFQzaqpAq7FXuYbGSQl9bNPw3vOqvbO+ari+XnKNs1nEtHHU/mkUmPEocw1SdIkvUHYhL+mUfiFuofpFOmp+ZiOzcROH2ckwABv0nxt70Fge5pXsDcDVQe8NfIqgDApKoyL5vKjg27ScOXjKyhc+vq1KJY6H52ZVOFYQlVWogIhQi0c+UWC/ZEUCjKF4Xh73SIfOTF+uiPa6jaKdIsaBHJQXxs/Ht7gCXXnpwA/uwDzHyPXWz4+LP+ARAf+HDtha5m8zae5WmY1e2gar4sMOmq4u+bLxp93Pd1+FNiEs3EyxXEbdvDS/z5TSuLGkPFBxHZRfWMcYJdabTJ6Tc47m7FE3QL9EPC/OxmWk0lRAXIOox0nAS0MYV6Nuf4xc9B2OvZ5RkCqMzDviHqm63bqcBfkXQhAVJc="
script:
  - ./mvnw test verify sonar:sonar -Pcoverage -B
git:
  depth: false
