language: java
jdk: openjdk11
sudo: required

services:
  - docker
  - postgresql

before_script:
  - psql -c 'create database notification-service;' -U johan


after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh

cache:
  directories:
    - $HOME/.m2
