package com.hedvig.notificationService.service

object TextKeys {

    const val DEFAULT_TITLE = "DEFAULT_TITLE"

    const val NEW_MESSAGE_BODY = "NEW_MESSAGE_BODY"

    const val REFERRAL_SUCCESS_BODY = "REFERRAL_SUCCESS_BODY"

    const val CONNECT_DD_TITLE = "NOTIFICATION_CONNECT_DD_TITLE"
    const val CONNECT_DD_BODY = "NOTIFICATION_CONNECT_DD_BODY"

    const val PAYMENT_FAILED_TITLE = "NOTIFICATION_PAYMENT_FAILED_TITLE"
    const val PAYMENT_FAILED_BODY = "NOTIFICATION_PAYMENT_FAILED_BODY"

    const val CLAIM_PAID_TITLE = "CLAIM_PAID_TITLE"
    const val CLAIM_PAID_BODY = "CLAIM_PAID_BODY"

    const val INSURANCE_POLICY_UPDATED_TITLE = "INSURANCE_POLICY_UPDATED_TITLE"
    const val INSURANCE_POLICY_UPDATED_BODY = "INSURANCE_POLICY_UPDATED_BODY"

    const val INSURANCE_RENEWED_TITLE = "INSURANCE_RENEWED_TITLE"
    const val INSURANCE_RENEWED_BODY = "INSURANCE_RENEWED_BODY"

    const val REFERRALS_ENABLED_TITLE = "REFERRALS_ENABLED_TITLE"
    const val REFERRALS_ENABLED_BODY = "REFERRALS_ENABLED_BODY"
}
